# Generated by Django 5.0.3 on 2024-04-07 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('connection_type', models.CharField(choices=[('LORA', 'Lora'), ('UKF', 'Ukf'), ('VHF', 'Vhf'), ('GSM', 'Gsm'), ('KF', 'Kf'), ('CB', 'Cb'), ('PMR', 'Pmr'), ('NA', 'Unknown')], default='NA', max_length=4)),
                ('frequency', models.IntegerField()),
                ('called', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='called', to='node.node')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caller', to='node.node')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_connections', to='node.node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
